version: '3'

volumes:
  vendor-store:
  node_modules-store:
  #unixドメインソケットを使う為に名前付きボリュームを設定（名前付きボリューム : マウントするホストのディレクトリを指定しない。）
  # バインドマウント : マウントするホストのディレクトリを指定する。
  php-fpm-socket:

services:
  php:
    tty: true
    platform: linux/x86_64 
    container_name: php
    build: 
      context: ./docker/php #Dockerfileが存在するディレクトリの相対パス
    volumes:
    # - php-fpm-socket:/var/run/php-fpm
    # - ./web:/var/www
    - vendor-store:/var/www/laravel/vendor
    - node_modules-store:/var/www/laravel/node_modules
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db

  nginx:
    platform: linux/x86_64 
    image: nginx
    container_name: nginx
    build: 
      context: ./docker/nginx
    ports:
    - 8080:80
    volumes:
    - php-fpm-socket:/var/run/php-fpm
    - ./web:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    platform: linux/x86_64 
    # image: mysql:8.0
    container_name: db
    build: ./docker/db #Dockerfileが存在するディレクトリの相対パス
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_project
      MYSQL_USER: ussii39
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # - grant all privileges on laravel_project.* TO 'ussii39'@'127.0.0.1' identified by 'password';
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

    