FROM nginx:1.17-alpine

# ローカルから設定ファイルをコピー
COPY  ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./defaultLocal.conf /etc/nginx/conf.d/default.conf




# VOLUME ./web:/var/www
# VOLUME  /../web/ /var/www
# COPY  default.conf /etc/nginx/conf.d/default.conf
# COPY  nginx.conf /etc/nginx/nginx.conf
